Add Canal View
robx/pzprjs pull request #231
Opened 2020-12-03 12:44 UTC by montelucci

to do: rules

2021-03-05 19:22 UTC, x-sheep requested changes

2021-03-05 19:22 UTC, x-sheep commented on src/variety/nurikabe.js
> +			"checkNumberAndShadeView",
Can you move `checkNumberAndShadeView` above `checkConnectShade`?

2021-03-05 19:22 UTC, x-sheep commented on src/variety/nurikabe.js
> +				return cell.qnum !== -1;
Question marks aren't checked, but are still updated. Maybe filter out all qnums below 0?

2021-03-05 20:59 UTC, x-sheep approved these changes

2022-09-06 10:58 UTC, merged

2022-09-06 10:58 UTC, robx commented
Thanks!