Add Evolmino
robx/pzprjs pull request #402
Opened 2023-03-15 21:43 UTC by subaru-saito1

I've implemeted a new type puzzle "Evolmino" ("シンカミノ: Shinkamino", in Japanese)
It's the latest puzzle appeared in Puzzle Publication Nikoli vol.182 (published on March 10th).

Rules and sample problem are here (Puzzle Square JP)
https://puzsq.logicpuzzle.app/puzzle/106378

2023-03-16 10:51 UTC, x-sheep commented
Thanks for the Pull Request! This genre looks very interesting.

I'll do a code review at a later date, but I have a few points, some of which are from our testers:

* [ ] I'd like a separate one-button and two-button mouse input. See the puzzles with `use: true` inside `MouseEvent` for an example.
* [ ] Clicking the mouse in Edit mode cycles between Invalid Cell, Rectangle and Empty. This makes it impossible to add given Rectangles on top of an arrow using the left mouse button. I'd like the order of items to be reversed.
* [ ] I'd like to be able to expand an existing arrow by dragging from the tail end.

2023-03-16 17:57 UTC, subaru-saito1 commented
Thanks for feedback!
I'll try to implement them later!

2023-03-17 06:47 UTC, subaru-saito1 commented
I've fixed cell and arrow input UI!

- Implement switching 2-button/1-button mode both play and edit mode.
- Swap left and right click cycle of cell input (when in play mode + 1-button mode)
- Improve arrow input UI to be able to expand reverse direction from arrow tail.

2023-03-17 20:49 UTC, x-sheep requested changes

2023-03-17 20:49 UTC, x-sheep commented on src/variety/evolmino.js
> +					if (dir === 1) {
Can you use the `LT` `RT` `UP` `DN` constants here?

2023-03-17 20:49 UTC, x-sheep commented on test/script/evolmino.js
> +			"arInvalid",
I think this check doesn't need to be shown on the rules page. Can you add `skiprules: true`?

2023-03-18 04:54 UTC, subaru-saito1 commented
Thank you for reveiwing! I fixed them.

2023-03-22 08:05 UTC, x-sheep approved these changes
This implementation looks good to me. I only have a few minor points, but I can also apply these changes myself if needed.

I'm planning to release this genre on Monday. Thank you for your work 🎉

2023-03-24 15:03 UTC, x-sheep commented
@subaru-saito1 A different question unrelated to Evolmino:

Do you still have the PDF's of the unused Omopa genres that used to be on your blog? I think some of them would be interesting to add to puzz.link 👀

2023-03-25 04:03 UTC, subaru-saito1 commented
@x-sheep 
I reuploaded those Omopa genres here: https://note.com/subaru_saito/n/ned95450dd181
I'll be add some problems and translate into English at a later date.

2023-03-27 15:54 UTC, merged

2023-03-27 16:12 UTC, x-sheep commented
[Evolmino is now available.](https://puzz.link/p?evolmino)

If you want your existing puzzles to be picked up by [the database](https://puzz.link/db/), you'll have to Tweet them again with the puzz.link URL.