Add Curving Road
robx/pzprjs pull request #538
Opened 2024-06-20 14:11 UTC by Seren-35

Source: http://inabapuzzle.com/honkaku/curving.html

In edit mode, I made circle placement follow the same behavior as shaded cells in dynasty genres, since two circles can never be adjacent in a solvable puzzle, whereas circles one empty cell apart seem to be a common pattern in puzzles I've seen.

When checking for paths that turn only once, at most one erroneous path per circle is highlighted. There can be quadratically many of those in total so highlighting all of them in sufficiently wrong answers can easily cover most of the grid and turn it unreadable. This seemed like a good compromise.

2024-06-20 14:55 UTC, Seren-35 commented
Apparently CI actually got mad at me for CR LF line endings this time. No clue why since I haven't done anything differently.

2024-06-21 09:07 UTC, x-sheep requested changes
Thanks for the contribution! I like how the error highlighting looks.

2024-06-21 09:07 UTC, x-sheep commented on test/script/kabingurodo.js
> +	inputs: []
The functions in `MouseEvent` are not covered by tests. Could you add a few input tests for the Editing part here?

2024-06-21 15:14 UTC, Seren-35 commented
Just occurred to me I should also test what happens when placing a circle on top of a shaded cell. This apparently throws an exception but, as best as I can tell, not because of my code - the combination of `numberRemainsUnshaded: true` and `edit: ["circle-unshade"]` seems to just do this.

2024-06-21 15:22 UTC, x-sheep approved these changes
Thanks for doing the changes. I'm going to release San-Anko on monday, and this genre 2 weeks after.

2024-07-08 07:57 UTC, merged